version: '3.7'

networks:
  traefik-proxy-network:
    name: proxy-net

services:
  traefik:
    image: traefik:v2.5
    ports:
      - "80:80"
      - "443:443" # 用于 TLS 即 HTTPS
      - "8080:8080"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json
      - ./log:/log
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: traefik
    env_file: .env
    networks:
      - traefik-proxy-network
    labels:
      - "traefik.docker.network:proxy-net"
      - "traefik.enable=true"
    # labels:
      # - "traefik.http.routers.api.rule=Host(`traefik.firefly.com`)"
      # - "traefik.http.routers.api.service=api@internal"

      # 配置 TLS
      # - traefik.http.routers.api.tls=true
      # 设置 https，此时certresolver 为 le，与 traefik.toml certificatesResolvers 配置保持一致
      # - traefik.http.routers.api.tls.certresolver=le
