apiVersion: apps/v1
kind: Deployment
metadata:
  name: cra-deployment
spec:
  selector:
    matchLabels:
      app: cra
  replicas: 3
  template:
    metadata:
      labels:
        app: cra
    spec:
      containers:
      - name: cra-deploy
        image: cra-deploy-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: cra-service
spec:
  selector:
    # 根据 Label 匹配应用
    app: cra
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
