version: "3"
services:
  route:
    build:
      context: .
      dockerfile: router.Dockerfile
    ports:
      - 3000:80

  route-brotli:
    build:
      context: .
      dockerfile: router-brotli.Dockerfile
    ports:
      - 4000:80
