# 通过此配置可在 Docker 环境中学习 nginx 的各种指令
# 如果需要修改配置，验证配置是否生效，可通过 docker-compose 重新启动该容器
version: "3"
services:
  api:
    image: shanyue/whoami
    ports:
      - 8888:3000
  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  location:
    image: nginx:alpine
    ports:
      - 8100:80
    volumes:
      - ./location.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  location2:
    image: nginx:alpine
    ports:
      - 8120:80
    volumes:
      - ./location2.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  order1:
    image: nginx:alpine
    ports:
      - 8210:80
    volumes:
      - ./order1.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  order2:
    image: nginx:alpine
    ports:
      - 8220:80
    volumes:
      - ./order2.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  order3:
    image: nginx:alpine
    ports:
      - 8230:80
    volumes:
      - ./order3.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  order4:
    image: nginx:alpine
    ports:
      - 8240:80
    volumes:
      - ./order4.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  proxy:
    image: nginx:alpine
    ports:
      - 8300:80
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  50x:
    image: nginx:alpine
    ports:
      - 8400:80
    volumes:
      - ./50x.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  gzip:
    image: nginx:alpine
    ports:
      - 8500:80
    volumes:
      - ./gzip.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  # 如何为 nginx 中添加 module
  # https://github.com/nginxinc/docker-nginx/tree/master/modules
  brotli:
    build:
      context: ./brotli/
      args:
        ENABLED_MODULES: brotli
    ports:
      - 8600:80
    volumes:
      - ./brotli.conf:/etc/nginx/conf.d/default.conf
      - ./brotli-nginx.conf:/etc/nginx/nginx.conf
      - .:/usr/share/nginx/html